---
# Cleanup installation

# Stop Zookeeper container
- name: Stop container
  docker_container:
    name: "{{ zk_name }}"
    keep_volumes: no
    state: absent

# Remove created directories
- name: Remove directories
  file:
    path: "{{ item }}"
    state: absent
  with_items:
    - "{{ zk_conf_dir }}"
    - "{{ zk_logs_dir }}"
    - "{{ zk_data_dir }}"
